name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: "php:${{ matrix.php }}"
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        service: ['mysql:5.7', mariadb]
        prefix: ['', flarum_]
        experimental: [false]

        include:
          - service: 'mysql:5.7'
            db: MySQL
          - service: mariadb
            db: MariaDB
          - prefix: flarum_
            prefixStr: (prefix)
          - php: '8.0'
            service: 'mysql:5.7'
            experimental: true

        exclude:
          - php: 7.2
            service: 'mysql:5.7'
            prefix: flarum_
          - php: 7.2
            service: mariadb
            prefix: flarum_
          - php: 7.3
            service: 'mysql:5.7'
            prefix: flarum_
          - php: 7.3
            service: mariadb
            prefix: flarum_

    services:
      mysql:
        image: ${{ matrix.service }}
        ports:
          - 13306:3306

    name: 'PHP ${{ matrix.php }} / ${{ matrix.db }} ${{ matrix.prefixStr }}'

    steps:
      - uses: actions/checkout@master

      - name: Create MySQL Database
        run: |
          sudo systemctl start mysql
          mysql -uroot -proot -e 'CREATE DATABASE flarum_test;' --port 13306

      - name: Install Composer dependencies
        run: composer install

      - name: Setup Composer tests
        run: composer test:setup
        env:
          DB_PORT: 13306
          DB_PASSWORD: root
          DB_PREFIX: ${{ matrix.prefix }}

      - name: Run Composer tests
        run: composer test
